package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/jsp/nav.html");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Application Administration</title>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js\"></script>\n");
      out.write("<link type=\"text/css\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/cupertino/jquery-ui.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/scienceworkflow.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/container/assets/skins/sam/container.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/resize/assets/skins/sam/resize.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/layout/assets/skins/sam/layout.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/button/assets/skins/sam/button.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.8.0r4/build/paginator/assets/skins/sam/paginator.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.8.0r4/build/datatable/assets/skins/sam/datatable.css\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/yahoo/yahoo-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/event/event-min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/dom/dom-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/element/element-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/dragdrop/dragdrop-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/container/container-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/resize/resize-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/animation/animation-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/layout/layout-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.8.0r4/build/datasource/datasource-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.8.0r4/build/datatable/datatable-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.8.1/build/paginator/paginator-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/connection/connection-min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jsonrpc.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  var selectedAppName = null;\n");
      out.write("  var jsonrpc;\n");
      out.write("\n");
      out.write("  function displayScriptApps(appName){\n");
      out.write("    // remove the old selection\n");
      out.write("    if ( appName == selectedAppName )\n");
      out.write("         return;\n");
      out.write("    scriptTable.deleteRows(scriptTable.getRecordSet().getLength() - 1, -1* scriptTable.getRecordSet().getLength());\n");
      out.write("    var result = jsonrpc.AppMgr.showAllScripts(appName);\n");
      out.write("    for( var i=0; i<result.list.length; i++){\n");
      out.write("             var newparam = new Object();\n");
      out.write("             newparam.name = result.list[i].scriptName;\n");
      out.write("             newparam.version = result.list[i].version;\n");
      out.write("             newparam.checkInTime = \"null\";\n");
      out.write("             newparam.byuser = \"null\";\n");
      out.write("             scriptTable.addRow(newparam, i);\n");
      out.write("    }\n");
      out.write("    scriptTable.render();\n");
      out.write("    selectedAppName = appName;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function onStatusChange(el)\n");
      out.write("  {\n");
      out.write("      var record = myDataTable.getRecord(el);\n");
      out.write("      var appName = record.getData(\"name\");\n");
      out.write("      var isEnabled = el.checked;\n");
      out.write("      if( isEnabled ) {\n");
      out.write("         jsonrpc.AppMgr.deployApplication(appName);\n");
      out.write("      } \n");
      out.write("      else {\n");
      out.write("         jsonrpc.AppMgr.disableApplication(appName);\n");
      out.write("      }\n");
      out.write("  }\n");
      out.write("\n");
      out.write("\n");
      out.write("   // CellEditor function\n");
      out.write("  function updateAppStatus(callback, newValue){\n");
      out.write("   var record = this.getRecord();\n");
      out.write("   var oldValue = this.value;\n");
      out.write("   var column = this.getColumn();\n");
      out.write("   var appName = record.getData(\"name\");\n");
      out.write("   if ( oldValue != newValue && newValue == 'deployed') {\n");
      out.write("        jsonrpc.AppMgr.deployApplication(appName);\n");
      out.write("   }\n");
      out.write("   callback(true, newValue);\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" var Dom = YAHOO.util.Dom,\n");
      out.write("     Event = YAHOO.util.Event,\n");
      out.write("     layout = null,\n");
      out.write("     resize = null;\n");
      out.write("\n");
      out.write("     Event.onDOMReady(function() {\n");
      out.write("        //layout = new YAHOO.widget.Layout( {\n");
      out.write("                    //minWidth: 1000,\n");
      out.write("                    //units: [\n");
      out.write("                        //{ position: 'top', height: 28, body: 'menu', scroll: null, zIndex: 2 },\n");
      out.write("                        //{ position: 'left', header: 'application list', body: 'apptable', gutter: '2px', width: 600, collapse:true  }, \n");
      out.write("                        //{ position: 'center',  header: 'script list', width: 800, resize: true, body: 'scriptlist', gutter: '0 5 0 2', minWidth:  600, maxWidth: 800 }\n");
      out.write("                    //]\n");
      out.write("                //});\n");
      out.write("        //layout.render();\n");
      out.write("        jsonrpc = new JSONRpcClient(\"");
      out.print(request.getContextPath());
      out.write("/Old-JSONRPC\");\n");
      out.write("            \n");
      out.write("       var myColumnDefs = [\n");
      out.write("     // {key:\"Select\", label:\"Select\", resizeable:true,formatter:\"radio\",hidden:true}, \n");
      out.write("      {key:\"name\", label:\"Application\", resizeable:true, sortable:true },\n");
      out.write("     // {key:\"url\", label: \"XML Description\", resizeable:true, sortable:true, hidden:true, \n");
      out.write("        //editor:new YAHOO.widget.TextareaCellEditor()\n");
      out.write("     //     }, \n");
      out.write("      {key:\"type\", label:\"Type\", resizable:true, sortable:true },\n");
      out.write("      {key:\"status\", label: \"Enabled\", resizeable:true, sortable:true, \n");
      out.write("       //editor:new YAHOO.widget.DropdownCellEditor({dropdownOptions:[\"created\", \"deployed\"], asyncSubmitter: updateAppStatus})\n");
      out.write("       }\n");
      out.write("      ];\n");
      out.write("     \n");
      out.write("      var myDataSource = new YAHOO.util.DataSource([]); \n");
      out.write("      myDataSource.responseType = YAHOO.util.DataSource.TYPE_JSARRAY; \n");
      out.write("      myDataSource.responseSchema = { fields: [\"name\", \"url\", \"status\"] };\n");
      out.write("   \n");
      out.write("      myDataTable = new YAHOO.widget.ScrollingDataTable(\"apptable\", myColumnDefs, myDataSource, {}); \n");
      out.write("      myDataTable.subscribe(\"rowMouseoverEvent\", myDataTable.onEventHighlightRow);\n");
      out.write("      myDataTable.subscribe(\"rowMouseoutEvent\", myDataTable.onEventUnhighlightRow);\n");
      out.write("      //myDataTable.subscribe(\"cellClickEvent\", function(oArgs){ \n");
      out.write("          //var target = oArgs.target;\n");
      out.write("\t  //var column = myDataTable.getColumn(target);\n");
      out.write("          //if (column.key == 'Select'){\n");
      out.write("            //var rec = this.getRecord(target);\n");
      out.write("            //displayScriptApps(rec.getData('name'));\n");
      out.write("          //} else \n");
      out.write("             //myDataTable.onEventShowCellEditor(oArgs);\n");
      out.write("      //});\n");
      out.write("\n");
      out.write("      var result = jsonrpc.AppMgr.showEveryApplication();\n");
      out.write("      result.list.sort( function(a,b) { if( a.appName < b.appName ) { return -1 } else { return 1 } } )\n");
      out.write("      for( var i=0; i<result.list.length; i++){\n");
      out.write("          var newparam = new Object();\n");
      out.write("          newparam.name = result.list[i].appName;\n");
      out.write(" \t      var url = result.list[i].xmldesfile;\n");
      out.write("          if (url== null) \n");
      out.write("              url = \"not defined\";\n");
      out.write("          newparam.url = url;\n");
      out.write("          newparam.type = result.list[i].type;\n");
      out.write("          //newparam.status = result.list[i].status;\n");
      out.write("          if( result.list[i].status === \"deployed\" )\n");
      out.write("              newparam.status = \"<input type=checkbox checked=true name=status value=created onClick=onStatusChange(this)>\"\n");
      out.write("          else\n");
      out.write("              newparam.status = \"<input type=checkbox name=status value=created onClick=onStatusChange(this)>\"\n");
      out.write("          myDataTable.addRow(newparam, i);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      myDataTable.render();\n");
      out.write("      \n");
      out.write("   });   \n");
      out.write("\n");
      out.write("   \n");
      out.write("   function saveUpdate (){\n");
      out.write("     /** for(i=0; i<changes.modified.length; i++){\n");
      out.write("              var modified = changes.modified[i];\n");
      out.write("              if (modified.status == 'deployed')\n");
      out.write("                 jsonrpc.AppMgr.deployApplication(modified.name);\n");
      out.write("     } **/\n");
      out.write("\n");
      out.write("     // handle the deleted script application\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"yui-skin-sam\">\n");
      out.write("  ");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"../css/screen.css\" />\n");
      out.write("<link type=\"text/css\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/cupertino/jquery-ui.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#menu {\n");
      out.write("\t/* float:left; */\n");
      out.write("\twidth:60%;\n");
      out.write("        margin-left:auto;\n");
      out.write("        margin-right:auto;\n");
      out.write("\tbackground:#efefef;\n");
      out.write("\tline-height:normal;\n");
      out.write("\tborder-bottom:1px solid #666;\n");
      out.write("    /* padding: 10px 0px 25px 0px; */\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-style: normal;\n");
      out.write("\t}\n");
      out.write("#menu ul {\n");
      out.write("\tmargin:0;\n");
      out.write("\t/* padding:10px 10px 0 50px; */\n");
      out.write("\tlist-style:none;\n");
      out.write("\t}\n");
      out.write("#menu li {\n");
      out.write("\tdisplay:inline;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0;\n");
      out.write("\t}\n");
      out.write("/*\n");
      out.write("#menu a {\n");
      out.write("\tfloat:left;\n");
      out.write("\tbackground:url(\"../images/tableftF.gif\") no-repeat left top;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0 0 0 4px;\n");
      out.write("\ttext-decoration:none;\n");
      out.write("\t}\n");
      out.write("#menu a span {\n");
      out.write("\tfloat:left;\n");
      out.write("\tdisplay:block;\n");
      out.write("\tbackground:url(\"../images/tabrightF.gif\") no-repeat right top;\n");
      out.write("\t/* padding:5px 15px 4px 6px;*/\n");
      out.write("\tcolor:#666;\n");
      out.write("\t}\n");
      out.write("*/\n");
      out.write("\t\n");
      out.write("/* Commented Backslash Hack hides rule from IE5-Mac \\*/\n");
      out.write("#menu a span {float:none;}\n");
      out.write("/* End IE5-Mac hack */\n");
      out.write("#menu a:hover span {color:#FFFFFF;}\n");
      out.write("#menu a:hover {background-position:0% -42px;}\n");
      out.write("#menu a:hover span {background-position:100% -42px;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready( function() {\n");
      out.write("            document.getElementById(\"username\").innerHTML = user;\n");
      out.write("    });\n");
      out.write("    var user = \"");
      out.print(session.getAttribute("username") );
      out.write("\";\n");
      out.write("    </script>\n");
      out.write("<div id=\"menu\">\n");
      out.write("    <div style=\"float:left;padding-left:20px;padding-top:20px\">\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" height=\"40px\" title=\"Science Portal\">\n");
      out.write("    </div>\n");
      out.write("    <div style=\"float:right;padding-right:20px;padding-top:20px\">\n");
      out.write("        <div style=\"float:left\">Logged in as&nbsp;</div>\n");
      out.write("        <div id=username style=\"font-weight:bold;float:left\"></div>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/runApplications.jsp>Jobs</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/applist.jsp>Settings</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/logout.jsp>Logout</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div style=\"clear:both\"></div>\n");
      out.write("\n");
      out.write("  <div id='apptable' class='ui-widget'>\n");
      out.write("\t  <div class=\"heading\">Science Portal Applications</div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
