package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class createApplication_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/jsp/nav.html");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js\"></script>\n");
      out.write("<link type=\"text/css\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/cupertino/jquery-ui.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/scienceworkflow.css\" type=\"text/css\" rel=\"stylesheet\" />\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/swfupload.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/container/assets/skins/sam/container.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/resize/assets/skins/sam/resize.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/layout/assets/skins/sam/layout.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.7.0/build/button/assets/skins/sam/button.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.8.0r4/build/paginator/assets/skins/sam/paginator.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/2.8.0r4/build/datatable/assets/skins/sam/datatable.css\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/yahoo/yahoo-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/event/event-min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/dom/dom-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/element/element-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/dragdrop/dragdrop-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/container/container-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/resize/resize-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/animation/animation-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/layout/layout-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.8.0r4/build/datasource/datasource-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.8.0r4/build/datatable/datatable-min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/2.7.0/build/connection/connection-min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <script type=\"text/javascript\" src=\"../swfupload/swfupload.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"../js/swfupload.queue.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"../js/fileprogress.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"../js/handlers.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"../js/yui-app-builder.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jsonrpc.js\"></script>\n");
      out.write("<script type=text/javascript src=\"");
      out.print(request.getContextPath());
      out.write("/js/commandLineParser.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("     sessionID = \"");
      out.print( request.getSession().getId() );
      out.write("\";\n");
      out.write("\n");
      out.write("     var Dom = YAHOO.util.Dom,\n");
      out.write("     Event = YAHOO.util.Event,\n");
      out.write("     layout = null,\n");
      out.write("     resize = null;\n");
      out.write("     var commandlinedialog = null;\n");
      out.write("\n");
      out.write("     Event.onDOMReady(function() {\n");
      out.write("\n");
      out.write("\n");
      out.write("       \n");
      out.write("          //layout = new YAHOO.widget.Layout( {\n");
      out.write("                    //minWidth: 1000,\n");
      out.write("                    //units: [\n");
      out.write("                        //{ position: 'top', height: 28, body: 'menu', scroll: null, zIndex: 2 },\n");
      out.write("                        ////{ position: 'left', header: 'application description', body: 'appdesc', gutter: '2px', width: 200, collapse:true  }, \n");
      out.write("                        //{ position: 'center',  header: 'parameter list', width: 800, resize: true, body: 'appdef', gutter: '0 5 0 2', minWidth: 600, maxWidth: 800 },\n");
      out.write("//\n");
      out.write("                    //]\n");
      out.write("                //});\n");
      out.write("       //layout.render();\n");
      out.write("\n");
      out.write("        commandlinedialog = new YAHOO.widget.Dialog(\"commandlinedialog\",\n");
      out.write("                                                { width : \"auto\",\n");
      out.write("                                                          fixedcenter : true,\n");
      out.write("                                                          hideaftersubmit : true,\n");
      out.write("                                                          visible : false,\n");
      out.write("                                                          close : true,\n");
      out.write("                                                          constraintoviewport : true,\n");
      out.write("                                                          buttons : [ { text:\"Done\", handler:handleCommandLineSubmit, isDefault:true },\n");
      out.write("                                                            { text:\"Cancel\", handler:handleCommandLineCancel } ]\n");
      out.write("                                                });\n");
      out.write("\n");
      out.write("       YAHOO.widget.DataTable.prototype.deleteRowsBy = function (condition) {\n");
      out.write("\t\t\t\tvar start = 0, count = 0, current = 0, \n");
      out.write("\t\t\t\t\trecs = this.getRecordSet().getRecords();\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\twhile (current < recs.length) {\n");
      out.write("\t\t\t\t\tif (condition(recs[current].getData())) {\n");
      out.write("\t\t\t\t\t\tif (count === 0) {\n");
      out.write("\t\t\t\t\t\t\tstart = current;\n");
      out.write("\t\t\t\t\t\t\t//log('got one to delete at ' + start);\n");
      out.write("\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t//log('got 1 more to delete');\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\tcount++;\n");
      out.write("\t\t\t\t\t\tcurrent++;\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\tif (count) {\n");
      out.write("\t\t\t\t\t\t\t//log('deleting ' + count + ' rows starting at ' + start);\n");
      out.write("\t\t\t\t\t\t\trecs.splice(start, count);\n");
      out.write("\t\t\t\t\t\t\tcount = 0;\n");
      out.write("\t\t\t\t\t\t\tcurrent = start;\n");
      out.write("\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\tcurrent++;\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif (count) {\n");
      out.write("\t\t\t\t\t//log('deleting ' + count + ' rows starting at ' + start);\n");
      out.write("\t\t\t\t\trecs.splice(start, count);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t//log('rendering');\n");
      out.write("\t\t\t\tthis.render();\n");
      out.write("\t\t\t};\n");
      out.write("\n");
      out.write("       init();\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    function parseCommandLine() {\n");
      out.write("      cmdline = document.getElementById('cmdline').value\n");
      out.write("//console.log(\"cmdline = \" + cmdline )\n");
      out.write("      parsed = parseCommandLineArgsTypesEx2(cmdline)\n");
      out.write("      cmd = parsed['cmd']\n");
      out.write("      document.getElementById('name').value = cmd\n");
      out.write("      //document.getElementById('title').value = cmd\n");
      out.write("      document.getElementById('command').value = cmd\n");
      out.write("\n");
      out.write("      arglist = parsed['list']\n");
      out.write("      loadParamToTable(arglist,myDataTable)\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function handleCommandLineSubmit() {\n");
      out.write("       //console.log(\"command line submitted\")\n");
      out.write("       parseCommandLine()\n");
      out.write("       this.cancel()\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function handleCommandLineCancel() {\n");
      out.write("       ////console.log(\"command line cancelled\")\n");
      out.write("       this.cancel()\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function enterCommandLine() {\n");
      out.write("        commandlinedialog.render(YAHOO.util.Dom.get('appdef'));\n");
      out.write("        commandlinedialog.cfg.setProperty(\"visible\", true);\n");
      out.write("        document.getElementById('cmdline').focus()\n");
      out.write("\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // define a group of variables for the application builder\n");
      out.write("  jsonrpc = new JSONRpcClient(\"");
      out.print(request.getContextPath());
      out.write("/Old-JSONRPC\");\n");
      out.write(" \n");
      out.write("  //console.log(\"created json store\");\n");
      out.write("\n");
      out.write("\n");
      out.write(" </script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\" yui-skin-sam\" style=\"text-align:left\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"../css/screen.css\" />\n");
      out.write("<link type=\"text/css\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/cupertino/jquery-ui.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#menu {\n");
      out.write("\t/* float:left; */\n");
      out.write("\twidth:60%;\n");
      out.write("        margin-left:auto;\n");
      out.write("        margin-right:auto;\n");
      out.write("\tbackground:#efefef;\n");
      out.write("\tline-height:normal;\n");
      out.write("\tborder-bottom:1px solid #666;\n");
      out.write("    /* padding: 10px 0px 25px 0px; */\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-style: normal;\n");
      out.write("\t}\n");
      out.write("#menu ul {\n");
      out.write("\tmargin:0;\n");
      out.write("\t/* padding:10px 10px 0 50px; */\n");
      out.write("\tlist-style:none;\n");
      out.write("\t}\n");
      out.write("#menu li {\n");
      out.write("\tdisplay:inline;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0;\n");
      out.write("\t}\n");
      out.write("/*\n");
      out.write("#menu a {\n");
      out.write("\tfloat:left;\n");
      out.write("\tbackground:url(\"../images/tableftF.gif\") no-repeat left top;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0 0 0 4px;\n");
      out.write("\ttext-decoration:none;\n");
      out.write("\t}\n");
      out.write("#menu a span {\n");
      out.write("\tfloat:left;\n");
      out.write("\tdisplay:block;\n");
      out.write("\tbackground:url(\"../images/tabrightF.gif\") no-repeat right top;\n");
      out.write("\t/* padding:5px 15px 4px 6px;*/\n");
      out.write("\tcolor:#666;\n");
      out.write("\t}\n");
      out.write("*/\n");
      out.write("\t\n");
      out.write("/* Commented Backslash Hack hides rule from IE5-Mac \\*/\n");
      out.write("#menu a span {float:none;}\n");
      out.write("/* End IE5-Mac hack */\n");
      out.write("#menu a:hover span {color:#FFFFFF;}\n");
      out.write("#menu a:hover {background-position:0% -42px;}\n");
      out.write("#menu a:hover span {background-position:100% -42px;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready( function() {\n");
      out.write("            document.getElementById(\"username\").innerHTML = user;\n");
      out.write("    });\n");
      out.write("    var user = \"");
      out.print(session.getAttribute("username") );
      out.write("\";\n");
      out.write("    </script>\n");
      out.write("<div id=\"menu\">\n");
      out.write("    <div style=\"float:left;padding-left:20px;padding-top:20px\">\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" height=\"40px\" title=\"Science Portal\">\n");
      out.write("    </div>\n");
      out.write("    <div style=\"float:right;padding-right:20px;padding-top:20px\">\n");
      out.write("        <div style=\"float:left\">Logged in as&nbsp;</div>\n");
      out.write("        <div id=username style=\"font-weight:bold;float:left\"></div>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/runApplications.jsp>Jobs</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/applist.jsp>Settings</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/logout.jsp>Logout</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div style=\"clear:both\"></div>\n");
      out.write("\n");
      out.write(" \n");
      out.write("<div id=\"appdef\" class=\"sw-main ui-widget\">\n");
      out.write("\n");
      out.write("   <div id=\"gadget-preview\" class=\"yui-pe-content\">\n");
      out.write("      <div class=\"bd\"></div>\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("   <div id=\"appdesc\">\n");
      out.write("   <br/><br/>\n");
      out.write("        <div class=\"ui-widget-header\">Define Application </div>\n");
      out.write("        <div class=\"ui-widget-content\">\n");
      out.write("        <div style=\"width:300px\">\n");
      out.write("     \t<table col=\"2\">\n");
      out.write("    \t<tr>\n");
      out.write("      \t\t<td>Name </td>\n");
      out.write("      \t\t<td><input type=\"text\" class=\"text\" id = \"name\" name=\"name\" size=\"30\"  /> </td>\n");
      out.write("       </tr>\n");
      out.write("<!--\n");
      out.write("       <tr>\n");
      out.write("    \t    \t<td>Title </td>\n");
      out.write("      \t\t<td><input type=\"text\" class=\"text\" id = \"title\" name=\"title\" size=\"30\"  /> </td>\n");
      out.write("       </tr>\n");
      out.write("-->\n");
      out.write("       <tr>\n");
      out.write("     \t\t<td>Command </td>\n");
      out.write("      \t\t<td><input type=\"text\" class=\"text\" id = \"command\" name=\"command\" size=\"30\" /> </td>\n");
      out.write("       </tr>\n");
      out.write("<!--\n");
      out.write("       <tr>\n");
      out.write("    \t       <td>Version </td>\n");
      out.write("      \t\t<td><input type=\"text\" class=\"text\" id = \"version\" name=\"version\" size=\"30\" /> </td>\n");
      out.write("   \t</tr>\n");
      out.write("    \t<tr>\n");
      out.write("      \t\t<td>Web Site </td>\n");
      out.write("      \t\t<td><input type=\"text\" class=\"text\" name=\"web site\" size=\"30\" /> </td>\n");
      out.write("   \t</tr>\n");
      out.write("-->\n");
      out.write("   \t\n");
      out.write("       </table>\n");
      out.write("       <div style=\"float:right;text-align:right\">\n");
      out.write("         <a href=\"javascript:openApplication();\">Load existing application</a><br>\n");
      out.write("         <a href=\"javascript:enterCommandLine();\">Enter command line</a>\n");
      out.write("       </div>\n");
      out.write("       <div style=\"clear:both\"></div>\n");
      out.write("       </div>\n");
      out.write("       </div>\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<br/>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function addRow() { myDataTable.addRow({}); }\n");
      out.write("\n");
      out.write("function goToApplication() {  hideNotification() } \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div class=\"ui-widget-header\">Parameter Definitions</div>\n");
      out.write("<div class=\"ui-widget-content\">\n");
      out.write("  <div style=\"font-size:77%\">Define the parameters for your application.</div>\n");
      out.write("  <div id=\"paralist\"></div>\n");
      out.write("  <a onClick=\"addRow()\" style=\"padding:5px;\" href=\"#\" class=\"insert-button\" alt=\"Add row\">&nbsp;&nbsp;</a>\n");
      out.write("  <button onClick=\"createXML()\" >Preview Application</button>\n");
      out.write("</div>\n");
      out.write("<br/>\n");
      out.write("\n");
      out.write("<div class=\"ui-widget-header\">Application Preview</div>\n");
      out.write("<div class=\"ui-widget-content\">\n");
      out.write("  <div style=\"font-size:77%\">This is how your application will appear to users. Adjust the parameters and preview the application until you're satisfied, then create the application.</div>\n");
      out.write("  <div id=\"placeholder\" style=\"width:300px;margin:10px\"><div class=\"ui-state-highlight\"><br/><span style=\"float: left; margin-right: 0.3em;\" class=\"ui-icon ui-icon-alert\"></span>Application preview not yet generated.<br/><br/></div>\n");
      out.write("<div style=\"clear:both\"></div>\n");
      out.write("</div>\n");
      out.write("<div style=\"clear:both\"></div>\n");
      out.write("</div>\n");
      out.write("<br/>\n");
      out.write("<div id=\"buttons\">\n");
      out.write("   <button onClick=\"commitApplication()\">Create Application</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div style=\"clear:both\"></div>\n");
      out.write("\n");
      out.write("<div id=\"notification\" style=\"font-size:12px;display:none; position: absolute; width: 600px; height: 30px;margin-left:auto;margin-right:auto; top: 10px; padding: 10px;line-height:2em;\" class=\"ui-widget ui-widget-content ui-corner-all ui-state-highlight\"><div id=\"msg\" style=\"float:left\"></div>\n");
      out.write("\t<div style=\"float:right\"><a href=javascript:hideNotification()>Close</a>\t\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"dialog1\" class=\"yui-pe-content\">\n");
      out.write("    <div class=\"hd\">Open Application</div>\n");
      out.write("    <div id=\"apptable\"> </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"commandlinedialog\" class=\"yui-pe-content\">\n");
      out.write("     <div class=\"hd\">Command Line Dialog</div>\n");
      out.write("     <div class=\"bd\">\n");
      out.write("       <div id=\"commandlineblock\" style=\"display:hidden\">\n");
      out.write("       Type the command line just as you would execute it in a shell to have it parsed into the table below.\n");
      out.write("       <p>\n");
      out.write("       <input id='cmdline' type=text onkeydown=\"if (event.keyCode == 13) { parseCommandLine(); commandlinedialog.cancel(); } \" size=80 value=\"app -a 1 -b 2 --longarg='longarg' --longarg2\"></input>\n");
      out.write("     </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
