package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class runApplications_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/jsp/nav.html");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \n");
      out.write("\"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n");
      out.write("\n");

 response.setHeader("Cache-Control","no-store"); 
 response.setHeader("Pragma","no-cache"); 
 response.setDateHeader ("Expires", 0);


      out.write("\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<meta name=\"language\" content=\"en\" />\n");
      out.write("\n");
      out.write("\t<title>Gadget Workspace Run Applications</title>\n");
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/layout-default-latest.css\" />\n");
      out.write("<!--\n");
      out.write("        <LINK rel=\"stylesheet\" type=\"text/css\" href=\"../css/themes/base/ui.core.css\">\n");
      out.write("        <LINK rel=\"stylesheet\" type=\"text/css\" href=\"../css/themes/base/ui.tabs.css\">\n");
      out.write("        <LINK rel=\"stylesheet\" type=\"text/css\" href=\"../css/themes/base/ui.all.css\">\n");
      out.write("        <LINK rel=\"stylesheet\" type=\"text/css\" href=\"../css/ui-1.7.1-demos.css\">\n");
      out.write("-->\n");
      out.write("        <LINK rel=\"stylesheet\" type=\"text/css\" href=\"../css/layout-default.css\">\n");
      out.write("<link type=\"text/css\" href=\"http://www.mcs.anl.gov/~turam/css/cupertino/jquery-ui-1.7.2.custom.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<!-- CUSTOMIZE/OVERRIDE THE DEFAULT CSS -->\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\n");
      out.write("\t    /* remove padding and scrolling from elements that contain an Accordion OR a content-div */\n");
      out.write("\t    .ui-layout-center ,\t/* has content-div */\n");
      out.write("\t    .ui-layout-west \t/* has Accordion */\n");
      out.write("\t    .ui-layout-content { /* content-div has Accordion */\n");
      out.write("\t\t    padding: 0;\n");
      out.write("\t\t    //overflow: scroll;\n");
      out.write("\t    }\n");
      out.write("\t    .ui-layout-north P.ui-layout-content {\n");
      out.write("\t\t    line-height:\t1.4em;\n");
      out.write("            }\n");
      out.write("\t    .ui-layout-northcentral P.ui-layout-content {\n");
      out.write("\t\t    line-height:\t1.4em;\n");
      out.write("            }\n");
      out.write("\t    .ui-layout-center P.ui-layout-content {\n");
      out.write("\t\t    line-height:\t1.4em;\n");
      out.write("\t\t    margin:\t\t\t0; /* remove top/bottom margins from <P> used as content-div */\n");
      out.write("                    overflow: visible;\n");
      out.write("\t\t    //overflow: scroll;\n");
      out.write("\t    }\n");
      out.write("\t    h3, h4 { /* Headers & Footer in Center & East panes */\n");
      out.write("\t\t    font-size:\t\t1.1em;\n");
      out.write("\t\t    background:\t\t#EEF;\n");
      out.write("\t\t    border:\t\t\t1px solid #BBB;\n");
      out.write("\t\t    border-width:\t0 0 1px;\n");
      out.write("\t\t    padding:\t\t7px 10px;\n");
      out.write("\t\t    margin:\t\t\t0;\n");
      out.write("\t    }\n");
      out.write("            body {\n");
      out.write("\t\t\tfont-size: 12px;\n");
      out.write("\t\t\tfont-family: Myriad,Helvetica,Tahoma,Arial,clean,sans-serif;\n");
      out.write("\t    }\n");
      out.write("\t</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <STYLE type=\"text/css\">\n");
      out.write("\n");
      out.write("                /*\n");
      out.write("                 *      TAB-THEME ADJUSTMENTS\n");
      out.write("                 */\n");
      out.write("                .ui-tabs-nav li {\n");
      out.write("                        white-space:    nowrap;\n");
      out.write("                }\n");
      out.write("                .ui-tabs-nav li a {\n");
      out.write("                        font-size:              1em !important;\n");
      out.write("                        padding:                4px 1.5ex 3px !important;\n");
      out.write("                }\n");
      out.write("                .ui-tabs-panel {\n");
      out.write("                        font-size:              1em !important;\n");
      out.write("                        padding:                0 1em !important;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                /*\n");
      out.write("                 *      WEST-PANE TABS\n");
      out.write("                 *\n");
      out.write("                 *      These tabs 'fill' the pane,\n");
      out.write("                 *      so the pane-border acts as the tab-border\n");
      out.write("                 */\n");
      out.write("                .ui-layout-pane-west {\n");
      out.write("                        padding:        0;\n");
      out.write("                        }\n");
      out.write("                        .ui-layout-pane-west .ui-tabs-nav {\n");
      out.write("                                /* don't need border or rounded corners - tabs 'fill' the pane */\n");
      out.write("                                border-top:             0;\n");
      out.write("                                border-left:    0;\n");
      out.write("                                border-right:   0;\n");
      out.write("                                padding-bottom: 0 !important;\n");
      out.write("                                -moz-border-radius:             0;\n");
      out.write("                                -webkit-border-radius:  0;\n");
      out.write("                        }\n");
      out.write("\n");
      out.write("         </STYLE>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- REQUIRED scripts for layout widget -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"oopsdemo/lib/js/jquery-1.3.2.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"oopsdemo/lib/js/jquery-ui-1.7.2.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"oopsdemo/lib/js/jquery.layout-1.3.rc5.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"oopsdemo/lib/js/debug.js\"></script>\n");
      out.write("       <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jsonrpc.js\"></script>\n");
      out.write("\n");
      out.write("        <SCRIPT type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("               $(document).ready( function() {\n");
      out.write("\n");
      out.write("                        document.getElementById(\"username\").innerHTML = user;\n");
      out.write("\n");
      out.write("                        // TABS-WEST - sortable\n");
      out.write("                        $(\".ui-layout-west-tabs\")\n");
      out.write("                                .tabs()\n");
      out.write("                                .find(\".ui-tabs-nav\")\n");
      out.write("                                        .sortable({ axis: 'x', zIndex: 2 })\n");
      out.write("                        ;\n");
      out.write("\n");
      out.write("                        // TABS-CENTER - sortable\n");
      out.write("                        $(\".ui-layout-center-tabs\")\n");
      out.write("                                //.tabs({selected:selectedTab})\n");
      out.write("                                .tabs({selected:0})\n");
      out.write("                                .find(\".ui-tabs-nav\")\n");
      out.write("                                        .sortable({ axis: 'x', zIndex: 2 })\n");
      out.write("                        ;\n");
      out.write(" /*\n");
      out.write("\n");
      out.write("                        // PAGE LAYOUT\n");
      out.write("                        $('body').layout({\n");
      out.write("                                west__size:                     $('body').innerWidth() * 0.2\n");
      out.write("\t\t\t,\twest__onresize:\t\t'westLayout.resizeAll'\n");
      out.write("\t\t\t,\tcenter__onresize:\t'eastLayout.resizeAll'\n");
      out.write("                        });\n");
      out.write("*/\n");
      out.write("                });\n");
      out.write("        </SCRIPT>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t    $(document).ready( function() {\n");
      out.write("               my.init();\n");
      out.write("               my.renderGadgets();\n");
      out.write("               my.listGadgets();\n");
      out.write("               my.selectGadget()\n");
      out.write("               my.changeSimGadget()\n");
      out.write("\t    });\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("<!-- default container look and feel -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/gadgets.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"/gadgets/js/pubsub.js?c=1&debug=1\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/util.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/gadgets.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\tvar user = \"");
      out.print(session.getAttribute("username") );
      out.write("\";\n");
      out.write("    var selectedTab = '");
      out.print( request.getParameter("app")==null?1:0 );
      out.write("'\n");
      out.write("    var selectedApp = '");
      out.print( request.getParameter("app")==null?"":request.getParameter("app")  );
      out.write("'\n");
      out.write("\tvar my = {};\n");
      out.write("\tvar webroot = \"http://\"+document.location.hostname+\":\"+document.location.port+\"/\";\n");
      out.write("\tmy.gadgetSpecUrls = [\n");
      out.write("\t webroot+\"");
      out.print(request.getContextPath());
      out.write("/gadgets/stub.xml\",\n");
      out.write("\t webroot+\"");
      out.print(request.getContextPath());
      out.write("/gadgets/preview.xml\",\n");
      out.write("\t webroot+\"");
      out.print(request.getContextPath());
      out.write("/gadgets/wfhistory.xml\",\n");
      out.write("\t];\n");
      out.write("\t\n");
      out.write("\tmy.LayoutManager = function() {\n");
      out.write("\t  gadgets.LayoutManager.call(this);\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\tmy.LayoutManager.inherits(gadgets.LayoutManager);\n");
      out.write("\t\n");
      out.write("\tmy.LayoutManager.prototype.getGadgetChrome = function(gadget) {\n");
      out.write("\t  var chromeId = 'gadget-chrome-' + gadget.id;\n");
      out.write("\t  return chromeId ? document.getElementById(chromeId) : null;\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\tmy.init = function() {\n");
      out.write("\t  gadgets.pubsubrouter.init(function(id) {\n");
      out.write("\t    return my.gadgetSpecUrls[parseInt(id[id.length - 1])];\n");
      out.write("\t  }, {\n");
      out.write("\t    onSubscribe: function(sender, channel) {\n");
      out.write("\t      log(sender + \" subscribes to channel '\" + channel + \"'\");\n");
      out.write("\t      // return true to reject the request.\n");
      out.write("\t    },\n");
      out.write("\t    onUnsubscribe: function(sender, channel) {\n");
      out.write("\t      log(sender + \" unsubscribes from channel '\" + channel + \"'\");\n");
      out.write("\t      // return true to reject the request.\n");
      out.write("\t    },\n");
      out.write("\t    onPublish: function(sender, channel, message) {\n");
      out.write("\t      log(sender + \" publishes '\" + message + \"' to channel '\" + channel + \"'\");\n");
      out.write("\t      // return true to reject the request.\n");
      out.write("\t    }\n");
      out.write("\t  });\n");
      out.write("\t  gadgets.container.layoutManager = new my.LayoutManager();\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\tmy.renderGadgets = function() {\n");
      out.write("\t    var secureToken = user+\":\"+user+\":appid:cont:url:0\";\n");
      out.write("\t    for (var i = 0; i < my.gadgetSpecUrls.length; ++i) {\n");
      out.write("\t        var gadget = gadgets.container.createGadget(\n");
      out.write("\t            {specUrl: my.gadgetSpecUrls[i], secureToken:secureToken});\n");
      out.write("\t            //{specUrl: my.gadgetSpecUrls[i], title: (i ? \"Subscriber\" : \"Publisher\"), secureToken:secureToken });\n");
      out.write("\t        gadgets.container.addGadget(gadget);\n");
      out.write("\t        gadgets.container.renderGadget(gadget);\n");
      out.write("\t    }\n");
      out.write("\t};\n");
      out.write("\tmy.changeSimGadget = function(){\n");
      out.write("         var gadgetList = document.getElementById(\"gadgetList\");\n");
      out.write("         var newUrl = gadgetList.options[gadgetList.selectedIndex].value;\n");
      out.write("         //var url = document.getElementById(\"gadgetUrl\");\n");
      out.write("         //url.value = newUrl;\n");
      out.write("         var secureToken = user+\":\"+user+\":appid:cont:newUrl:0\";\n");
      out.write("         var gadget = gadgets.container.createGadget({specUrl: newUrl, secureToken: secureToken, id:0});\n");
      out.write("         // remove the old sim gadget in the container\n");
      out.write("         var chrome= document.getElementById(\"gadget-chrome-0\");\n");
      out.write("         while(chrome.firstChild){\n");
      out.write("           chrome.removeChild(chrome.firstChild);\n");
      out.write("         }\n");
      out.write("         gadgets.container.gadgets_[0] = gadget;          \n");
      out.write("         gadgets.container.renderGadget(gadget);\n");
      out.write("       };\n");
      out.write("    my.selectGadget = function(){\n");
      out.write("        var gadgetList = document.getElementById(\"gadgetList\");\n");
      out.write("        gadgetList.selectedIndex = gadgetList.options.length-1\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    my.listGadgets = function(){\n");
      out.write("        var jsonrpc = new JSONRpcClient(\"");
      out.print(request.getContextPath());
      out.write("/Old-JSONRPC\");\n");
      out.write("        var result = jsonrpc.AppMgr.showAllApplication();\n");
      out.write("        result.list.sort(function(a,b) { if( a.appName < b.appName ) { return -1 } else { return 1 } } )\n");
      out.write("        var gadgetList = document.getElementById(\"gadgetList\");\n");
      out.write("        gadgetList.remove(0)\n");
      out.write("        for( var i=0; i<result.list.length; i++){\n");
      out.write("\n");
      out.write("            // do not show \"script\" type applications; they'll be included by the showAllScripts block below\n");
      out.write("            if( result.list[i].type === \"cmd\") {\n");
      out.write("\n");
      out.write("                //display the gadgets\n");
      out.write("                // get the current server address\n");
      out.write("                var rootUrl = (document.location.href).split(\"/\");\n");
      out.write("\t            var gadgetUrl = rootUrl[0]+\"//\"+rootUrl[1]+rootUrl[2]+\"/SIDGridPortal/SIDGridGadgets/\"+result.list[i].appName+\".xml\";\n");
      out.write("\t            o = new Option(result.list[i].appName, gadgetUrl);\n");
      out.write("\t            gadgetList.options[gadgetList.length] = o;\n");
      out.write("            }\n");
      out.write("\t \n");
      out.write("            if (result.list[i].type == 'script'){\n");
      out.write("                var appName = result.list[i].appName;\n");
      out.write("  \t            var script_result = jsonrpc.AppMgr.showAllScripts(appName);\n");
      out.write("                if( script_result )  {\n");
      out.write("                    script_result.list.sort(function(a,b) { \n");
      out.write("                       if( a.scriptName < b.scriptName ) { return -1 } else { return 1 } \n");
      out.write("                       });\n");
      out.write(" \n");
      out.write("  \t                for( var j=0; j<script_result.list.length; j++) {\n");
      out.write("       \t                var rootUrl = (document.location.href).split(\"/\");\n");
      out.write("       \t                var scriptname = script_result.list[j].scriptName;\n");
      out.write("                        var gadgetUrl;\n");
      out.write("       \t                if (script_result.list[j].gadgetLink != null ) {\n");
      out.write("                            //gadgetUrl = script_result.list[j].gadgetLink;\n");
      out.write("                            var rootUrl = (document.location.href).split(\"/\");\n");
      out.write("\t                        var gadgetUrl = rootUrl[0]+\"//\"+rootUrl[1]+rootUrl[2]+\"/SIDGridPortal/SIDGridGadgets/\"+result.list[i].appName+\".xml\";\n");
      out.write("                            gadgetList.options[gadgetList.length] = new Option(scriptname , gadgetUrl);\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("  \t        }\n");
      out.write("       }\n");
      out.write("    }\n");
      out.write("\tfunction log(message) {\n");
      out.write("\t    document.getElementById(\"output\").innerHTML += gadgets.util.escapeString(message) + \"<br/>\";\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"../css/screen.css\" />\n");
      out.write("<link type=\"text/css\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/cupertino/jquery-ui.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#menu {\n");
      out.write("\t/* float:left; */\n");
      out.write("\twidth:60%;\n");
      out.write("        margin-left:auto;\n");
      out.write("        margin-right:auto;\n");
      out.write("\tbackground:#efefef;\n");
      out.write("\tline-height:normal;\n");
      out.write("\tborder-bottom:1px solid #666;\n");
      out.write("    /* padding: 10px 0px 25px 0px; */\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-style: normal;\n");
      out.write("\t}\n");
      out.write("#menu ul {\n");
      out.write("\tmargin:0;\n");
      out.write("\t/* padding:10px 10px 0 50px; */\n");
      out.write("\tlist-style:none;\n");
      out.write("\t}\n");
      out.write("#menu li {\n");
      out.write("\tdisplay:inline;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0;\n");
      out.write("\t}\n");
      out.write("/*\n");
      out.write("#menu a {\n");
      out.write("\tfloat:left;\n");
      out.write("\tbackground:url(\"../images/tableftF.gif\") no-repeat left top;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0 0 0 4px;\n");
      out.write("\ttext-decoration:none;\n");
      out.write("\t}\n");
      out.write("#menu a span {\n");
      out.write("\tfloat:left;\n");
      out.write("\tdisplay:block;\n");
      out.write("\tbackground:url(\"../images/tabrightF.gif\") no-repeat right top;\n");
      out.write("\t/* padding:5px 15px 4px 6px;*/\n");
      out.write("\tcolor:#666;\n");
      out.write("\t}\n");
      out.write("*/\n");
      out.write("\t\n");
      out.write("/* Commented Backslash Hack hides rule from IE5-Mac \\*/\n");
      out.write("#menu a span {float:none;}\n");
      out.write("/* End IE5-Mac hack */\n");
      out.write("#menu a:hover span {color:#FFFFFF;}\n");
      out.write("#menu a:hover {background-position:0% -42px;}\n");
      out.write("#menu a:hover span {background-position:100% -42px;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready( function() {\n");
      out.write("            document.getElementById(\"username\").innerHTML = user;\n");
      out.write("    });\n");
      out.write("    var user = \"");
      out.print(session.getAttribute("username") );
      out.write("\";\n");
      out.write("    </script>\n");
      out.write("<div id=\"menu\">\n");
      out.write("    <div style=\"float:left;padding-left:20px;padding-top:20px\">\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" height=\"40px\" title=\"Science Portal\">\n");
      out.write("    </div>\n");
      out.write("    <div style=\"float:right;padding-right:20px;padding-top:20px\">\n");
      out.write("        <div style=\"float:left\">Logged in as&nbsp;</div>\n");
      out.write("        <div id=username style=\"font-weight:bold;float:left\"></div>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/runApplications.jsp>Jobs</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/applist.jsp>Settings</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/logout.jsp>Logout</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div style=\"clear:both\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"ui-layout-north\" style=\"display: none;\">\n");
      out.write("            ");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"../css/screen.css\" />\n");
      out.write("<link type=\"text/css\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/cupertino/jquery-ui.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#menu {\n");
      out.write("\t/* float:left; */\n");
      out.write("\twidth:60%;\n");
      out.write("        margin-left:auto;\n");
      out.write("        margin-right:auto;\n");
      out.write("\tbackground:#efefef;\n");
      out.write("\tline-height:normal;\n");
      out.write("\tborder-bottom:1px solid #666;\n");
      out.write("    /* padding: 10px 0px 25px 0px; */\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-style: normal;\n");
      out.write("\t}\n");
      out.write("#menu ul {\n");
      out.write("\tmargin:0;\n");
      out.write("\t/* padding:10px 10px 0 50px; */\n");
      out.write("\tlist-style:none;\n");
      out.write("\t}\n");
      out.write("#menu li {\n");
      out.write("\tdisplay:inline;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0;\n");
      out.write("\t}\n");
      out.write("/*\n");
      out.write("#menu a {\n");
      out.write("\tfloat:left;\n");
      out.write("\tbackground:url(\"../images/tableftF.gif\") no-repeat left top;\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0 0 0 4px;\n");
      out.write("\ttext-decoration:none;\n");
      out.write("\t}\n");
      out.write("#menu a span {\n");
      out.write("\tfloat:left;\n");
      out.write("\tdisplay:block;\n");
      out.write("\tbackground:url(\"../images/tabrightF.gif\") no-repeat right top;\n");
      out.write("\t/* padding:5px 15px 4px 6px;*/\n");
      out.write("\tcolor:#666;\n");
      out.write("\t}\n");
      out.write("*/\n");
      out.write("\t\n");
      out.write("/* Commented Backslash Hack hides rule from IE5-Mac \\*/\n");
      out.write("#menu a span {float:none;}\n");
      out.write("/* End IE5-Mac hack */\n");
      out.write("#menu a:hover span {color:#FFFFFF;}\n");
      out.write("#menu a:hover {background-position:0% -42px;}\n");
      out.write("#menu a:hover span {background-position:100% -42px;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready( function() {\n");
      out.write("            document.getElementById(\"username\").innerHTML = user;\n");
      out.write("    });\n");
      out.write("    var user = \"");
      out.print(session.getAttribute("username") );
      out.write("\";\n");
      out.write("    </script>\n");
      out.write("<div id=\"menu\">\n");
      out.write("    <div style=\"float:left;padding-left:20px;padding-top:20px\">\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" height=\"40px\" title=\"Science Portal\">\n");
      out.write("    </div>\n");
      out.write("    <div style=\"float:right;padding-right:20px;padding-top:20px\">\n");
      out.write("        <div style=\"float:left\">Logged in as&nbsp;</div>\n");
      out.write("        <div id=username style=\"font-weight:bold;float:left\"></div>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/runApplications.jsp>Jobs</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/applist.jsp>Settings</a>&nbsp;\n");
      out.write("        <a href=");
      out.print(request.getContextPath());
      out.write("/jsp/logout.jsp>Logout</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div style=\"clear:both\"></div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"ui-layout-west\" style=\"float:left;width:18%;margin:5px;\">\n");
      out.write("\t    <DIV id=\"left_column_tabs\" class=\"ui-widget\">\n");
      out.write("\t        <DIV class=\"sw-header ui-widget-header ui-corner-all\" style=\"padding:5px;font-weight:normal;font-size:14px\">\n");
      out.write("\t        Workflows\n");
      out.write("            </DIV>\n");
      out.write("\t        <DIV class=\"ui-widget-content\">\n");
      out.write("\t            <DIV id=\"tabs-west-1\">     \n");
      out.write("\t                <div id=\"gadget-chrome-2\" class=\"gadgets-gadget-chrome\" style=\"float:left;\"></div>\n");
      out.write("                    </DIV>\n");
      out.write("\t        </DIV>\n");
      out.write("\t    </DIV>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<div class=\"ui-layout-center\" style=\"display: block;float:left;width:79%;margin:0px;\"> \n");
      out.write("\t    <DIV id=\"main_app_tabs\" class=\"ui-layout-center-tabs\" style=\"height:100%;margin:3px\">\n");
      out.write("\t        <UL style='padding:0'>                \n");
      out.write("\t            <LI><A href=\"#tabs-center-1\">Run Simulations</A></LI>\n");
      out.write("\t            <LI><A href=\"#tabs-center-2\">View Results</A></LI>\n");
      out.write("\t        </UL>        \n");
      out.write("\t    \n");
      out.write("\t        <!-- add wrapper that Layout will auto-size to 'fill space' -->   \n");
      out.write("\t        <DIV class=\"ui-layout-content\">\n");
      out.write("\t            <DIV id=\"tabs-center-1\">     \n");
      out.write("                       <select id=\"gadgetList\" onchange=\"my.changeSimGadget();\">\n");
      out.write("                          <option value=\"/SIDGridGadgets/sgflow/sgflow(1)/sgflow.xml\">sgflow(1)</option>\n");
      out.write("                       </select>\n");
      out.write("\n");
      out.write("\t                <div id=\"gadget-chrome-0\" class=\"gadgets-gadget-chrome\" style=\"float:left;width:100%\"></div>\n");
      out.write("\t            </DIV>\n");
      out.write("\t            <DIV id=\"tabs-center-2\">  \n");
      out.write("\t                <div id=\"gadget-chrome-1\" class=\"gadgets-gadget-chrome\" style=\"float:left;width:100%\"></div>\n");
      out.write("\t            </DIV>\n");
      out.write("\t        </DIV><!--- END content-body --->\n");
      out.write("\t    </DIV>\n");
      out.write("\t\n");
      out.write("\t    <div id=\"output\" style=\"clear: left;display:none\"></div>\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html> \n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
